[package]
name = "year2025"
version = "0.1.0"
edition = "2024"

[dependencies]
adventofcode = { version = "0.1.0", path = "../adventofcode" }
indicatif = { version = "0.18.3", features = ["rayon"] }
itertools = "0.14.0"
petgraph = "0.8.3"
rayon = "1.11.0"
regex = "1.12.2"
